### ISSUE TITLE
0.15.0 support

### ISSUE THREAD

**Issue by File14** [Encritary/ServerCobweb#1]
Hello! 

Can you please update this to 0.15.0? 

This might help you: https://github.com/Nukkit/Nukkit/commit/7705f2e621f3bd1559f1175307f1c8b0d8cb4ff8

Best Regards,
File14

**Comment by MrGenga** [comment]
There is not working. I want to continue developing for 0.14.0, and then 0.15.0 support

**Comment by xZeroMCPE** [comment]
Maybe you"ll be able to help out! 

https://github.com/BukkitPE/BungeeCordPE
